<?php

namespace Jluct\ConfiguratorServerBundle\Repository;

/**
 * FileConfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileConfRepository extends \Doctrine\ORM\EntityRepository
{
}
