<?php

namespace Jluct\ConfiguratorServerBundle\Repository;

/**
 * BlockConfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupConfRepository extends \Doctrine\ORM\EntityRepository
{
}
