<?php

namespace Jluct\ConfiguratorServerBundle\Repository;

/**
 * MeaningsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeaningsRepository extends \Doctrine\ORM\EntityRepository
{
}
