<?php

namespace Jluct\ConfiguratorServerBundle\Repository;

/**
 * PrimitiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrimitiveRepository extends \Doctrine\ORM\EntityRepository
{
}
