<?php

namespace Jluct\ConfiguratorServerBundle\Repository;

/**
 * StringConfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StringConfRepository extends \Doctrine\ORM\EntityRepository
{
}
