jluct_configurator_server_homepage:
    path:     /
    defaults: { _controller: JluctConfiguratorServerBundle:Default:index }

jluct_configurator_server_add_data:
    path:     /add-test-data
    defaults: { _controller: JluctConfiguratorServerBundle:Default:addData }

jluct_configurator_server_get_file_config:
    path: /file/{id}
    defaults: {_controller: JluctConfiguratorServerBundle:Default:getSettingFile}
    methods: [GET]
    requirements:
        id: '\d+'